Controllers/ChatController.cs
namespace OpenAIAssessment.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class ChatController : Controller
    {
        public IActionResult Index()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View();
        }
    }
}

Controllers/HomeController.cs
namespace OpenAIAssessment.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View();
        }
    }
}

Controllers/ImageGenerationController.cs
namespace OpenAIAssessment.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class ImageGenerationController : Controller
    {
        public IActionResult Index()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View();
        }
    }
}

Controllers/TextEditController.cs
namespace OpenAIAssessment.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class TextEditController : Controller
    {
        public IActionResult Index()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View();
        }
    }
}

Views/Chat/Index.cshtml
<h2>AI Chat</h2>

@section scripts
{
    <script type="module" src="~/pages/chat-page.js" asp-append-version="true"></script>
}

<div>
    <chat-page></chat-page>
</div>

Views/Home/Index.cshtml
<div class="container text-center mt-5">
    <h1>Welcome to the Chat Open AI Assessment</h1>
    <p>This website provides various functionalities:</p>

    <div class="row mt-4">
        <div class="col-md-4">
            <h3>Chat Functionality</h3>
            <p>Engage in interactive conversations with an AI assistant.</p>
            <a href="/Chat" class="btn btn-primary">Go to Chat</a>
        </div>
        <div class="col-md-4">
            <h3>Text Edit Functionality</h3>
            <p>Edit and manipulate text using advanced tools.</p>
            <a href="/TextEdit" class="btn btn-primary">Go to Text Edit</a>
        </div>
        <div class="col-md-4">
            <h3>Image Generation Functionality</h3>
            <p>Generate images based on specific descriptions.</p>
            <a href="/ImageGeneration" class="btn btn-primary">Go to Image Generation</a>
        </div>
    </div>
</div>

Views/ImageGeneration/Index.cshtml
<h2>Image Generation</h2>

@section scripts
{
    <script type="module" src="~/pages/imagegen-page.js" asp-append-version="true"></script>
}

<div>
    <imagegen-page></imagegen-page>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>OpenAIAssessment</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    @* Uncomment to use the HtmlEditor control *@
    @* <script src="https://unpkg.com/devextreme-quill@22_2/dist/dx-quill.min.js"></script> *@

    @* Uncomment to use the Gantt control *@
    @*<link href="~/css/devextreme/dx-gantt.css" rel="stylesheet" />*@

    @* Uncomment to use the Diagram control *@
    @*<link href="~/css/devextreme/dx-diagram.css" rel="stylesheet" />*@

    <link href="~/css/devextreme/bootstrap.css" rel="stylesheet" />

    @* Predefined themes: https://js.devexpress.com/DevExtreme/Guide/Themes_and_Styles/Predefined_Themes/ *@
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/Site.css" />

    @* Uncomment to use the Gantt control *@
    @*<script src="~/js/devextreme/dx-gantt.js"></script>*@

    @* Uncomment to use the Diagram control *@
    @*<script src="~/js/devextreme/dx-diagram.js"></script>*@

    <script src="~/js/devextreme/jquery.js"></script>
    <script src="~/js/devextreme/bootstrap.js"></script>

    @* Uncomment to use Globalize for localization *@
    @* Docs: https://docs.devexpress.com/AspNetCore/400577#globalize *@
    @*<script src="~/js/devextreme/cldr.js"></script>*@
    @*<script src="~/js/devextreme/cldr/event.js"></script>*@
    @*<script src="~/js/devextreme/cldr/supplemental.js"></script>*@
    @*<script src="~/js/devextreme/cldr/unresolved.js"></script>*@
    @*<script src="~/js/devextreme/globalize.js"></script>*@
    @*<script src="~/js/devextreme/globalize/message.js"></script>*@
    @*<script src="~/js/devextreme/globalize/number.js"></script>*@
    @*<script src="~/js/devextreme/globalize/currency.js"></script>*@
    @*<script src="~/js/devextreme/globalize/date.js"></script>*@

    @* Uncomment to enable client-side export *@
    @*<script src="~/js/devextreme/jszip.js"></script>*@

    <script src="~/js/devextreme/dx.all.js"></script>

    @* Uncomment to provide geo-data for the VectorMap control *@
    @* Docs: https://js.devexpress.com/DevExtreme/Guide/Widgets/VectorMap/Providing_Data/#Data_for_Areas *@
    @*<script src="~/js/devextreme/vectormap-data/world.js"></script>*@

    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js"></script>
</head>

<body style="padding-top: 5rem;">

    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">OpenAIAssessment</a>

            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navbar" class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item"><a class="nav-link active" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Chat" asp-action="Index">Chat</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="TextEdit" asp-action="Index">Text Edit</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="ImageGeneration" asp-action="Index">Image Generation</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <main class="container">
        @RenderBody()
    </main>

    @RenderSection("scripts", required: false)
</body>

</html>

Views/TextEdit/Index.cshtml
<h2>Text Edit</h2>

@section scripts
{
    <script type="module" src="~/pages/textedit-page.js" asp-append-version="true"></script>
}

<div>
    <textedit-page></textedit-page>
</div>